<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>

    <RootNamespace>FLRPC</RootNamespace>
    <AssemblyName>FLStudioRPC</AssemblyName>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.2.1.24" />
    <PackageReference Include="Colorful.Console" Version="1.2.15" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Tmds.DBus" Version="0.94.2" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.94.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Icons/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>